
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 15 21:18:34 CST 2013
//----------------------------------------------------

package clasesPrograma;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int VALINT = 13;
  public static final int COLOR = 12;
  public static final int COMA = 2;
  public static final int PCOMA = 3;
  public static final int RECTANGULO = 8;
  public static final int ENTER = 11;
  public static final int CERRARPAR = 5;
  public static final int INICIO = 6;
  public static final int FIN = 7;
  public static final int LINEA = 10;
  public static final int EOF = 0;
  public static final int CIRCULO = 9;
  public static final int error = 1;
  public static final int ABRIRPAR = 4;
}

